// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJIgriXlPdaovsRZMcQShLBUgeiPogK4w',
    appId: '1:592846401369:web:552f24d8a11f0047496648',
    messagingSenderId: '592846401369',
    projectId: 'rent-n-use-5a4b7',
    authDomain: 'rent-n-use-5a4b7.firebaseapp.com',
    storageBucket: 'rent-n-use-5a4b7.firebasestorage.app',
    measurementId: 'G-MTCQE21JZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxUfemq94xpPKCFz7ZZStQUn1Q7KIP8O4',
    appId: '1:592846401369:android:a2322d0dcdd158ad496648',
    messagingSenderId: '592846401369',
    projectId: 'rent-n-use-5a4b7',
    storageBucket: 'rent-n-use-5a4b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASExLV-KiF_Clm8gD_v3BuG0jWxcSS0xM',
    appId: '1:592846401369:ios:70d2c163044a124d496648',
    messagingSenderId: '592846401369',
    projectId: 'rent-n-use-5a4b7',
    storageBucket: 'rent-n-use-5a4b7.firebasestorage.app',
    iosBundleId: 'com.example.rentNUse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASExLV-KiF_Clm8gD_v3BuG0jWxcSS0xM',
    appId: '1:592846401369:ios:70d2c163044a124d496648',
    messagingSenderId: '592846401369',
    projectId: 'rent-n-use-5a4b7',
    storageBucket: 'rent-n-use-5a4b7.firebasestorage.app',
    iosBundleId: 'com.example.rentNUse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJIgriXlPdaovsRZMcQShLBUgeiPogK4w',
    appId: '1:592846401369:web:adef0583f0d7a2d2496648',
    messagingSenderId: '592846401369',
    projectId: 'rent-n-use-5a4b7',
    authDomain: 'rent-n-use-5a4b7.firebaseapp.com',
    storageBucket: 'rent-n-use-5a4b7.firebasestorage.app',
    measurementId: 'G-W3G7DYHREG',
  );
}
